framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'evert.albert@praetorianausicaa.com'
        headers:
            From: 'Evert <evert.albert@praetorianausicaa.com>'
