controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

###################### Admin #######################

admin:
    path: /admin
    controller: App\Controller\Admin\AdminController::indexAction

admin.membership_request.approve:
    path: /admin/membership-request/{membershipRequest}/approve
    controller: App\Controller\Admin\AdminController::approveMembershipRequest

admin.membership_request.deny:
    path: /admin/membership-request/{membershipRequest}/deny
    controller: App\Controller\Admin\AdminController::denyMembershipRequest

admin.group_activity.confirm:
    path: /admin/group-activity/{groupActivity}/confirm
    controller: App\Controller\Admin\CalendarAdminController::indexAction

admin.group_activity.remove:
    path: /admin/group-activity/{groupActivity}/remove
    controller: App\Controller\Admin\CalendarAdminController::removeGroupActivity

###################### Home #######################

login:
    path: /login
    controller: \App\Controller\SecurityController::login

logout:
    path: /logout
    controller: \App\Controller\SecurityController::logout

###################### Home #######################

home:
    path: /
    controller: App\Controller\HomeController::indexAction

###################### Calendar #######################

calendar:
    path: /calendar
    controller: App\Controller\CalendarController::indexAction

calendar.register:
    path: /calendar/register/{groupActivityId}
    controller: App\Controller\CalendarController::registerAction

###################### Photos #######################

photos:
    path: /photos
    controller: App\Controller\PhotoController::indexAction

photos.create_album:
    path: /photos/create_album
    controller: App\Controller\PhotoController::createAlbumAction

photos.upload:
    path: /photos/upload
    controller: App\Controller\PhotoController::temporaryUploadAction

###################### Team #######################

team:
    path: /team
    controller: App\Controller\TeamController::indexAction

###################### Join #######################

join:
    path: /join
    controller: App\Controller\JoinController::indexAction