controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

###################### Admin #######################

admin:
    path: /admin
    controller: App\Controller\AdminController::indexAction

admin.membership_request.approve:
    path: /admin/membership-request/{id}/approve
    controller: App\Controller\AdminController::approveMembershipRequest

admin.membership_request.deny:
    path: /admin/membership-request/{id}/deny
    controller: App\Controller\AdminController::denyMembershipRequest

###################### Home #######################

home:
    path: /
    controller: App\Controller\HomeController::indexAction

###################### Calendar #######################

calendar:
    path: /calendar
    controller: App\Controller\CalendarController::indexAction

calendar.register:
    path: /calendar/register/{groupActivityId}
    controller: App\Controller\CalendarController::registerAction

###################### Photos #######################

photos:
    path: /photos
    controller: App\Controller\PhotoController::indexAction

photos.upload:
    path: /photos/upload
    controller: App\Controller\PhotoController::temporaryUploadAction

###################### Team #######################

team:
    path: /team
    controller: App\Controller\TeamController::indexAction

###################### Join #######################

join:
    path: /join
    controller: App\Controller\JoinController::indexAction